### ISSUE TITLE
Library selection

### ISSUE THREAD

**Issue by phife-dawg** [LukeChannings/moviematch#2]
Would it be possible to add a env variable to select a library? Not sure how it is choosing right now, but when I run this it chooses my home video library

**Comment by LukeChannings** [comment]
Right now the library selection is [very simple](https://github.com/LukeChannings/moviematch/blob/main/src/api/plex.ts#L34). I can probably add something to make selecting a specific library easier.

**Comment by zellenberg** [comment]
I would love to write a PR but I am not much of a programmer. I'm not even sure what you are showing in that hyperlink :(

**Comment by jhelmink** [comment]
So `SECTION_TYPE_FILTER` defaults to `movie` if not supplied.

We retrieve all the Directories (aka Libraries) stored in Plex in `getSections()` using;
`http://[PMS_IP_Address]:32400/library/sections?X-Plex-Token=YourTokenGoesHere`
Each directory returned has a `type` associated with it (movie, show, artist)

We then do a `sections.MediaContainer.Directory.find()` based on `type="movie"`
My guess is that .find() only retrieves the first matching directory?
We then use the `key` (unique id) for the directory to retrieve the movies or shows in that directory (aka library)

Might be better to filter on title instead of type eg `title="Movies"` so users can specify the name of their specific Library to use.

https://support.plex.tv/articles/201638786-plex-media-server-url-commands/

**Comment by LukeChannings** [comment]
I've just released [v1.0.2](https://github.com/LukeChannings/moviematch/releases/tag/v1.0.2) with support for library selection.

To use it, pass `LIBRARY_FILTER=<Library Title>` as an environment variable. Multiple libraries can be specified with commas, e.g. `LIBRARY_FILTER=Movies,TV Shows`.

**Comment by phife-dawg** [comment]
@LukeChannings you are the best!
