### ISSUE TITLE
[Feature Request] Enhance the desktop layout 

### ISSUE THREAD

**Issue by GhostPyxel** [LukeChannings/moviematch#35]
**Is your feature request related to a problem? Please describe.**
The mobile experience of MovieMatch works like a charm but the current desktop ergonomy still lacks some keys elements.
The posters might be too zoomed in creating graphical artifacts and stretching over the current quality of the posters stored in Plex.

Matched items are also stored inline creating a scrollbar. It could make more sens to display them as a grid on desktop. 

**Describe the solution you'd like**
Create a more specific layout for Desktop.

**Comment by LukeChannings** [comment]
Hey,

I'm currently working on the implementation of a new design (the sketch file is [here](https://github.com/LukeChannings/moviematch/blob/dev/web/design/MovieMatch.sketch)).

The main focus is mobile, because that's the place most people will be using this app, but the Desktop experience is quite  a lot better.

As for the matches view - a horizontally scrolling list is very intuitive on macOS, and being able to see your matches as well as the next card is useful.

![iPad - No Matches](https://user-images.githubusercontent.com/461449/103824313-aa963880-5041-11eb-838b-a22538aaf9ef.jpg)
![iPad](https://user-images.githubusercontent.com/461449/103824331-b124b000-5041-11eb-8554-857a9a3d9293.jpg)
![iPhone 8](https://user-images.githubusercontent.com/461449/103824349-b7b32780-5041-11eb-9ce7-537d05c46cd8.jpg)
