### ISSUE TITLE
[Bug] - ROOT_PATH=/moviematch breaks site

### ISSUE THREAD

**Issue by rubadub-github** [LukeChannings/moviematch#45]
in my docker compose I have this == ROOT_PATH=/moviematch

Going to http://localhost:8000/moviematch gives me an error of "Not Found"

Going to http://localhost:8000/ brings up the site, but no images/icon load.  
The site is expecting them under /moviematch/assets/logo.svg but they're in /assets/logo.svg (for example)

I assumed that adding that root path would 'move' the site under /moviematch -- and with that allow it to work behind the reverse proxy.

Debug log -  https://pastebin.com/DTnv7hd0

**Comment by LukeChannings** [comment]
Hey @rubadub-github 

That's actually not what this setting does exactly.

- This option is meant to be used with a reverse proxy
- The reverse proxy should forward requests starting with `/moviematch` to the MovieMatch server (e.g. `http://localhost:8000/`

If you load MovieMatch directly when configured like this it won't work because it's expecting to go via the reverse proxy.

**Comment by rubadub-github** [comment]
ok - sent things through the swag proxy and the page loads and looks OK, however the 'engage' button doesn't do anything.  

Guess I'll I'll keep digging.

**Comment by rubadub-github** [comment]
I hadn't added this line, looks like it working now -
proxy_set_header Upgrade $http_upgrade;
