### ISSUE TITLE
[Bug] DNS Error when running docker container on Unraid

### ISSUE THREAD

**Issue by willrc627** [LukeChannings/moviematch#70]
**Describe the bug**
DNS Error when running docker container on Unraid:
> Uncaught (in promise) TypeError: error sending request for url (https://plex.local:32400/library/sections?X-Plex-Token=XXXX): error trying to connect: dns error: failed to lookup address information: Name or service not known

**To Reproduce** Docker Settings:
Network Type: Bridge, Host, or Custom: br0 w/ Fixed IP
PLEX_URL: https://plex.local:32400
PLEX_TOKEN: XXXX (Substitute for real token)

**Expected behavior**
Expected for docker container to run but error stops container

**Server**
- OS: Unraid
- Version: 6.9.1

**Smartphone (please complete the following information):**
Unable to make it this far in the installation

**Additional context**
Also attempted:
- Using the server's local IP instead of domain name
- Passing in DNS server info to the docker container

**Comment by LukeChannings** [comment]
Hey @willrc627 

This error occurs when the DNS request for `plex.local` doesn't resolve.

The reason for this error is likely unrelated to MovieMatch, and is specific to your network and execution environment. 

- Docker has its own DNS server for the containers it runs, and can't resolve local domains from your network (e.g. `plex.local`, `plex.lan`, etc).
- Try using the IP address instead of a domain name in these circumstances. 
- If you want Docker's DNS resolution to work like you expect, you can start with this bug - https://serverfault.com/questions/1030064/docker-cant-resolve-dns-names-outside-of-docker-network-receiving-read-from-dn
