### ISSUE TITLE
[Feature Request] Show brief details of movie

### ISSUE THREAD

**Issue by danshilm** [LukeChannings/moviematch#9]
I was thinking even a link to the agent (link to IMDb or TMDB) that matched the movie in Plex would be great to have for people who haven't ever heard of a movie that shows up in the selection. I'm not sure how a brief plot description would fit in the current UI, which is why I'm suggesting a button/link instead.

Bonus would be for a link to the movie trailer on Youtube.

**Comment by flying-sausages** [comment]
I think there should be just little enough info shown to the user to let them make a very quick decision instead of spending 2 minutes studying each card.

Also, I think most of this info is already aregated through Plex, so I think you can skip querying yet another source. If not, you should fix your metadata and might have some other problems ;)

**Comment by danshilm** [comment]
> 
> 
> I think there should be just little enough info shown to the user to let them make a very quick decision instead of spending 2 minutes studying each card.
> 
> Also, I think most of this info is already aregated through Plex, so I think you can skip querying yet another source. If not, you should fix your metadata and might have some other problems ;)

Correct. Then in that case, a link/button to the Plex movie should be a better feature request.
I have a decent amount of movies in my library that even I didn't ever watch nor know anything about, and having a quick way to get that little information would enable me to make a decision as to whether I want to give that movie a try or not.

**Comment by SerinitySW** [comment]
To add to this, querying plex for the movie's rating (rotten tomatoes) and showing a % rating by the description would also be helpful and a simple addition

**Comment by jemus42** [comment]
My idea would be basic info (title, year, poster) shown initially, with the option to e.g. tap the poster and get extra info for a second look, which could include a plot summary and the trailer. 
The idea would be to be able to make a very quick decision but have the option to (quickly) investigate further if you're interested but on the fence.

**Comment by LukeChannings** [comment]
This is the current design in the dev branch - 

https://user-images.githubusercontent.com/461449/103768863-43509800-4ff1-11eb-9c24-291edd97f10d.mov

I haven't thought about the rating or linking to the matcher yet. I think I'd probably link to Plex itself, since it usually has a "Play Trailer" option.

**Comment by Coleyra** [comment]
If there's a way to add the length of the movie, and the director / main cast, that would be great !

**Comment by domesticwarlord86** [comment]
> This is the current design in the dev branch  
@LukeChannings 

Any idea when these features will come live? Or if nothing else, can I pull this branch with docker? It's great having the synopsis of the movie on there.

**Comment by LukeChannings** [comment]
@domesticwarlord86 

There's still lots to do, but I'm hoping to release an alpha version in the next few weeks.
The first release will not be stable though, I warn you!

**Comment by domesticwarlord86** [comment]
> @domesticwarlord86
> 
> There's still lots to do, but I'm hoping to release an alpha version in the next few weeks.
> The first release will not be stable though, I warn you!

Fair enough! If you need any debugging help just let me know.

**Comment by LukeChannings** [comment]
@domesticwarlord86 

I released the first alpha version recently. There is a long list of known issues, but if you're curious you can try it out.

Release: [v2.0.0-alpha.1](https://github.com/LukeChannings/moviematch/releases/tag/v2.0.0-alpha.1)
[Extended known issues are here](https://github.com/LukeChannings/moviematch/blob/main/RELEASE_NOTES.markdown#v200-alpha1)

Standalone binaries are available and attached as assets on the aforelinked release page, so you can run it without Docker or Deno. The Docker tag for this release is (predictably) `v2.0.0-alpha.1`.

The `latest` tag will only be updated when 2.0.0 is released, but I might start automatically pushing the `develop` tag again when 2.0.0 starts to get stable (maybe `2.0.0-beta.1`), since I know some people are still pulling that image and likely don't want alpha-quality software.

**Comment by Coleyra** [comment]
For the releases (moviematch.exe for example), what's the naming of the config file ?
Maybe the release sould come with a template file, or the first launch create a default config file ?

`INFO No default config file found. Starting up with defaults until configured.`

**Comment by Coleyra** [comment]
> 
> 
> For the releases (moviematch.exe for example), what's the naming of the config file ?
> Maybe the release sould come with a template file, or the first launch create a default config file ?
> 
> `INFO No default config file found. Starting up with defaults until configured.`

Sorry i haven't seen the configuration screen when you launch the local url.

**Comment by LukeChannings** [comment]
No worries. I've added a little note about the configuration [here](https://github.com/LukeChannings/moviematch/blob/main/docs/configuration.markdown).

It's not really documented at all right now, I'll write some more extensive documentation when it starts to get more stable, that way I don't need to revisit it if it gets out of date during development.

**Comment by Coleyra** [comment]
Yeah, rewriting docs all the time is boring :D

this is the config file generated by moviematch.exe
`host: 127.0.0.1
port: 8888
servers:
  - url: 'http://127.0.0.1:32400'
    token: myToken
    type: plex
logLevel: INFO
basePath: localhost
requirePlexTvLogin: false`

But the port seems not working : 
`
INFO MovieMatch 2.0.0-alpha.1
INFO Server listening on http://0.0.0.0:8000
`

**Comment by LukeChannings** [comment]
Do you have a PORT also specified in your environment, or are your only using a config.yaml?

**Comment by Coleyra** [comment]
Well i don't know if i have a PORT specified in my environment, i just modified the config.yaml file generated by moviematch.exe

**Comment by LukeChannings** [comment]
When MM starts up it should log the running configuration (if it doesn't,
add "logLevel: debug" to your config.yaml).

Can you paste that log here?

**Comment by Coleyra** [comment]
logLevel: debug seem to do nothing

i always have this : 
INFO MovieMatch 2.0.0-alpha.1
INFO Server listening on http://0.0.0.0:8000

Or if i delete config.yaml : 
INFO No default config file found. Starting up with defaults until configured.
INFO MovieMatch 2.0.0-alpha.1
INFO Server listening on http://0.0.0.0:8000

But i don't think we should be talking about this here, is there a better place to talk about configuration stuff ?

**Comment by LukeChannings** [comment]
@Coleyra I've created a discussion, that might make more sense - https://github.com/LukeChannings/moviematch/discussions/55.

I'll release a second alpha version this weekend that will include much more robust configuration handling. Thanks for your patience!
